# GNU Readline library finder
if(READLINE_INCLUDE_DIR AND READLINE_LIBRARY)
   set(READLINE_FIND_QUIETLY TRUE)
endif(READLINE_INCLUDE_DIR AND READLINE_LIBRARY)

FIND_PATH(READLINE_INCLUDE_DIR readline/readline.h)
FIND_LIBRARY(READLINE_LIBRARY NAMES readline)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Readline DEFAULT_MSG READLINE_LIBRARY READLINE_INCLUDE_DIR )

MARK_AS_ADVANCED(READLINE_INCLUDE_DIR READLINE_LIBRARY)

